export const StrategicNodeType = {
    RALLY_CRY: 'RALLY_CRY',
    DEFINING_OBJECTIVE: 'DEFINING_OBJECTIVE',
    OUTCOME: 'OUTCOME',
    SUPPORTING_OUTCOME: 'SUPPORTING_OUTCOME',
};
export const PlanState = {
    DRAFT: 'DRAFT',
    LOCKED: 'LOCKED',
    RECONCILING: 'RECONCILING',
    RECONCILED: 'RECONCILED',
};
export const PlanEvent = {
    LOCK: 'LOCK',
    START_RECONCILIATION: 'START_RECONCILIATION',
    RECONCILE: 'RECONCILE',
};
export const CommitStatus = {
    DELIVERED: 'DELIVERED',
    PARTIAL: 'PARTIAL',
    MISSED: 'MISSED',
};
export const CarryDecision = {
    DROP: 'DROP',
    FINISHED_NEXT_WEEK: 'FINISHED_NEXT_WEEK',
    CARRY_FORWARD: 'CARRY_FORWARD',
};
export const ManagerReviewStatus = {
    PENDING: 'PENDING',
    APPROVED: 'APPROVED',
    NEEDS_DISCUSSION: 'NEEDS_DISCUSSION',
};
export const ExceptionType = {
    OVERDUE_LOCK: 'OVERDUE_LOCK',
    PENDING_REVIEW_SLA: 'PENDING_REVIEW_SLA',
    REPEATED_CARRY_FORWARD: 'REPEATED_CARRY_FORWARD',
    OUTCOME_COVERAGE_GAP: 'OUTCOME_COVERAGE_GAP',
    BLOCKED_HIGH_PRIORITY: 'BLOCKED_HIGH_PRIORITY',
};
//# sourceMappingURL=enums.js.map